# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes to /etc/nixos/configuration.nix instead.
{ config, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "acpi_call" ];
  boot.kernelParams = [ "i915.fastboot=1" "intel_iommu=on" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/cead3453-145b-49bc-803f-0ba39ec9d9b2";
    crypttabExtraOpts = [ "fido2-device=auto" ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/8fe2fbaf-ef3c-4ef3-8097-8d0c5eeda183";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/E6DD-D259";
      fsType = "vfat";
    };
  };

  zramSwap.enable = true;

  powerManagement.cpuFreqGovernor = "conservative";

  hardware = {
    enableAllFirmware = true;
    enableRedistributableFirmware = true;
    cpu.intel.updateMicrocode = true;
    trackpoint = {
      enable = true;
      emulateWheel = true;
    };
  };
}
