name: "Update flake.lock"

on: { schedule: [{ cron: '0 0 * * 0' }], workflow_dispatch }

jobs:
  updates:
    name: "Update the flake.lock"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v17
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210823_af94b54/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    # Update flake.lock
    - name : 'flake.lock: Update'
      run: |
        git config user.name 'Ilan Joselevich'
        git config user.email 'personal@ilanjoselevich.com'
        nix flake update --commit-lock-file
        git push
