name: "Update flake.lock"

on: { workflow_dispatch }

jobs:
  updates:
    name: "Update the flake.lock"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v19
    - name : 'flake.lock: Update'
      run: |
        git config user.name 'Ilan Joselevich'
        git config user.email 'personal@ilanjoselevich.com'
        nix flake update --commit-lock-file
        git push
